import type { Metadata, Viewport } from "next";
import Analytics from "@/components/Analytics";
import JsonLd from "@/components/JsonLd";
import StickyMobileCTA from "@/components/StickyMobileCTA";
import { getAbsoluteUrl, getOfficialProfileUrls, site } from "@/data/site";
import { publicText } from "@/utils/publicContent";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `Eastern Massage Spa | Massage Therapy in Issaquah, WA`,
    template: `%s | ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "Massage Issaquah",
    "Massage Therapy Issaquah WA",
    site.name,
    "Massage Spa Issaquah",
    "Advanced Recovery Therapy Issaquah",
    "Targeted Therapeutic Massage Issaquah",
    "Essential Relaxation Massage Issaquah",
    "Michelle Massage Therapist Issaquah",
    "Hot Stone Massage Issaquah",
    "Cupping Therapy Issaquah",
    "CBD Massage Issaquah",
    "Spa Issaquah",
  ],
  authors: [{ name: site.legalName, url: site.url }],
  creator: site.legalName,
  publisher: site.legalName,
  category: "Health & Wellness",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: `${site.name} | Massage Therapy in Issaquah, WA`,
    description: site.description,
    url: site.url,
    siteName: site.name,
    locale: "en_US",
    type: "website",
    images: [
      {
        url: site.images.og,
        width: 1200,
        height: 630,
        alt: `${site.name} treatment room in Issaquah`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} | Massage Therapy in Issaquah, WA`,
    description: site.description,
    images: [site.images.og],
  },
  icons: {
    icon: "/icon", // Matches the basePath + route generated by icon.tsx
  },
  alternates: {
    canonical: site.url,
  },
};

export const viewport: Viewport = {
  themeColor: "#3A4D3F",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const openingHoursSpecification = site.hoursConfirmed
    ? site.hours.flatMap((entry) =>
        "opens" in entry && "closes" in entry
          ? entry.days.map((day) => ({
              "@type": "OpeningHoursSpecification",
              dayOfWeek: day,
              opens: entry.opens,
              closes: entry.closes,
            }))
          : []
      )
    : undefined;

  const serviceCatalog = site.services.map((service) => ({
    "@type": "OfferCatalog",
    name: service.category,
    itemListElement: service.items.map((item) => {
      const numericPriceValue = item.price.replace(/[^0-9.]/g, "");
      const numericPrice = numericPriceValue ? Number(numericPriceValue) : NaN;
      const offer: Record<string, unknown> = {
        "@type": "Offer",
        name: `${service.category} - ${item.name}`,
        description: publicText(service.description, service.category),
      };

      if (!Number.isNaN(numericPrice)) {
        offer.price = numericPrice;
        offer.priceCurrency = "USD";
      }

      return offer;
    }),
  }));

  const addOnCatalog = {
    "@type": "OfferCatalog",
    name: "Massage Enhancements",
    itemListElement: site.addons.map((addon) => {
      const numericPriceValue = addon.price.replace(/[^0-9.]/g, "");
      const numericPrice = numericPriceValue ? Number(numericPriceValue) : NaN;
      const offer: Record<string, unknown> = {
        "@type": "Offer",
        name: addon.name,
        description: publicText(addon.description, addon.name),
      };

      if (!Number.isNaN(numericPrice)) {
        offer.price = numericPrice;
        offer.priceCurrency = "USD";
      }

      return offer;
    }),
  };

  const structuredData = [
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "@id": `${site.url}/#website`,
      url: site.url,
      name: site.name,
      description: site.description,
    },
    {
      "@context": "https://schema.org",
      "@type": ["HealthAndBeautyBusiness", "Spa"],
      "@id": `${site.url}/#business`,
      name: site.name,
      legalName: site.legalName,
      url: site.url,
      mainEntityOfPage: site.url,
      description: site.description,
      image: [getAbsoluteUrl(site.images.og), getAbsoluteUrl(site.images.hero)],
      logo: getAbsoluteUrl(site.images.logo),
      telephone: site.phoneE164,
      priceRange: site.priceRange,
      address: {
        "@type": "PostalAddress",
        streetAddress: site.address.streetAddress,
        addressLocality: site.address.addressLocality,
        addressRegion: site.address.addressRegion,
        postalCode: site.address.postalCode,
        addressCountry: site.address.addressCountry,
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: site.geo.latitude,
        longitude: site.geo.longitude,
      },
      hasMap: site.mapUrl,
      ...(openingHoursSpecification ? { openingHoursSpecification } : {}),
      areaServed: {
        "@type": "City",
        name: site.address.addressLocality,
      },
      sameAs: [site.mapUrl, ...getOfficialProfileUrls()],
      hasOfferCatalog: [...serviceCatalog, addOnCatalog],
      potentialAction: {
        "@type": "ReserveAction",
        target: site.bookingUrl,
      },
    },
  ];

  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-background text-foreground antialiased">
        <Analytics />
        <JsonLd id="site-structured-data" data={structuredData} />
        {children}
        <StickyMobileCTA />
      </body>
    </html>
  );
}
