import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import { site } from "@/data/site";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} | Massage Therapy in Issaquah, WA`,
    template: `%s | ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "Massage Issaquah",
    site.name,
    "Deep Tissue Massage Issaquah",
    "Swedish Massage Issaquah",
    "Mobile Massage Issaquah",
    "Hot Stone Massage",
    "Cupping Therapy",
    "Spa Issaquah",
  ],
  authors: [{ name: site.legalName, url: site.url }],
  creator: site.legalName,
  publisher: site.legalName,
  category: "Health & Wellness",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: `${site.name} | Issaquah, WA`,
    description: site.description,
    url: site.url,
    siteName: site.name,
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/photos/stock2.jpg",
        width: 1200,
        height: 630,
        alt: `${site.name} massage therapy room`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} | Issaquah, WA`,
    description: site.description,
    images: ["/photos/stock2.jpg"],
  },
  icons: {
    icon: "/icon", // Matches the basePath + route generated by icon.tsx
  },
  alternates: {
    canonical: site.url,
  },
};

export const viewport: Viewport = {
  themeColor: "#3A4D3F",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const telephone = site.phoneHref.replace("tel:", "+");
  const openingHoursSpecification = site.hours.flatMap((entry) =>
    entry.days.map((day) => ({
      "@type": "OpeningHoursSpecification",
      dayOfWeek: day,
      opens: entry.opens,
      closes: entry.closes,
    }))
  );

  const serviceCatalog = site.services.map((service) => ({
    "@type": "OfferCatalog",
    name: service.category,
    itemListElement: service.items.map((item) => {
      const numericPriceValue = item.price.replace(/[^0-9.]/g, "");
      const numericPrice = numericPriceValue ? Number(numericPriceValue) : NaN;
      const offer: Record<string, unknown> = {
        "@type": "Offer",
        name: `${service.category} - ${item.name}`,
        description: service.description,
      };

      if (!Number.isNaN(numericPrice)) {
        offer.price = numericPrice;
        offer.priceCurrency = "USD";
      }

      return offer;
    }),
  }));

  const addOnCatalog = {
    "@type": "OfferCatalog",
    name: "Enhancements",
    itemListElement: site.addons.map((addon) => {
      const numericPriceValue = addon.price.replace(/[^0-9.]/g, "");
      const numericPrice = numericPriceValue ? Number(numericPriceValue) : NaN;
      const offer: Record<string, unknown> = {
        "@type": "Offer",
        name: `Add-on: ${addon.name}`,
      };

      if (!Number.isNaN(numericPrice)) {
        offer.price = numericPrice;
        offer.priceCurrency = "USD";
      }

      return offer;
    }),
  };

  const structuredData = [
    {
      "@context": "https://schema.org",
      "@type": "HealthAndBeautyBusiness",
      name: site.name,
      legalName: site.legalName,
      url: site.url,
      image: [`${site.url}/photos/stock2.jpg`],
      telephone,
      priceRange: site.priceRange,
      address: {
        "@type": "PostalAddress",
        streetAddress: site.address.streetAddress,
        addressLocality: site.address.addressLocality,
        addressRegion: site.address.addressRegion,
        postalCode: site.address.postalCode,
        addressCountry: site.address.addressCountry,
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: site.geo.latitude,
        longitude: site.geo.longitude,
      },
      hasMap: site.mapUrl,
      openingHoursSpecification,
      areaServed: {
        "@type": "City",
        name: site.address.addressLocality,
      },
      sameAs: [site.mapUrl],
      hasOfferCatalog: [...serviceCatalog, addOnCatalog],
      potentialAction: {
        "@type": "ReserveAction",
        target: site.bookingUrl,
      },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: site.faqs.map((faq) => ({
        "@type": "Question",
        name: faq.question,
        acceptedAnswer: {
          "@type": "Answer",
          text: faq.answer,
        },
      })),
    },
  ];

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} antialiased bg-background text-foreground`}
      >
        <Script
          id="structured-data"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        {children}
      </body>
    </html>
  );
}
