import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://easternmassagespa.com"),
  title: {
    default: "Eastern Massage Spa | Massage Therapy in Issaquah, WA",
    template: "%s | Eastern Massage Spa",
  },
  description: "Relax and rejuvenate at Eastern Massage Spa in Issaquah. Professional Swedish, Deep Tissue, and Mobile massage services. Call (206) 750-6868 to book.",
  keywords: ["Massage Issaquah", "Eastern Massage Spa", "Deep Tissue Massage", "Swedish Massage", "Mobile Massage Issaquah", "Spa Issaquah", "Cupping Therapy", "Hot Stone Massage"],
  authors: [{ name: "Eastern Massage Spa" }],
  creator: "Eastern Massage Spa",
  publisher: "Eastern Massage Spa",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: "Eastern Massage Spa | Issaquah, WA",
    description: "Professional massage therapy including Swedish, Deep Tissue, and Cupping in a relaxing atmosphere.",
    url: "https://easternmassagespa.com",
    siteName: "Eastern Massage Spa",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/photos/stock1.jpg", // Ensure this path is correct relative to public
        width: 1200,
        height: 630,
        alt: "Eastern Massage Spa Interior",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Eastern Massage Spa | Issaquah, WA",
    description: "Relax and rejuvenate with our professional massage services.",
    images: ["/photos/stock1.jpg"],
  },
  icons: {
    icon: "/eastern-massage-spa/icon", // Matches the basePath + route generated by icon.tsx
  },
  alternates: {
    canonical: "https://easternmassagespa.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
